# Generated by Django 4.2.4 on 2023-09-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='заголовок')),
                ('blog', models.TextField(verbose_name='блог')),
                ('image', models.ImageField(upload_to='blog/', verbose_name='изображение')),
                ('quantity_views', models.IntegerField(verbose_name='количество просмотров')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='дата публикации')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='дата обновлении')),
            ],
        ),
    ]
