# Generated by Django 4.2.4 on 2023-09-01 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_email', '0003_alter_email_send_from_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_try_datetime', models.DateTimeField(auto_now=True, verbose_name='время последней попытки')),
                ('status', models.CharField(max_length=25, verbose_name='статус')),
                ('server_response', models.TextField(blank=True, null=True, verbose_name='ответ почтового сервера')),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_log', to='app_email.email')),
            ],
            options={
                'verbose_name': 'Логи рассылка',
                'verbose_name_plural': 'Логи рассылки',
            },
        ),
    ]
