# Generated by Django 4.2.4 on 2023-09-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='status',
            field=models.CharField(choices=[('Success', 'Успешно'), ('Failure', 'Не успешно')], max_length=25, verbose_name='статус'),
        ),
    ]
