# Generated by Django 4.2.4 on 2023-09-01 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_client', '0001_initial'),
        ('app_email', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='send_from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='отправитель'),
        ),
        migrations.AddField(
            model_name='email',
            name='send_to_client',
            field=models.ManyToManyField(related_name='client', to='app_client.client', verbose_name='получатель'),
        ),
    ]
