# Generated by Django 4.2.4 on 2023-09-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_email', '0003_alter_email_send_from_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('launched', 'Launched'), ('finished', 'Finished')], default=('created', 'Created'), max_length=35, verbose_name='статус'),
        ),
    ]
