# Generated by Django 4.2.4 on 2023-09-01 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_email', '0006_alter_email_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='status',
            field=models.CharField(choices=[('C', 'Создана'), ('L', 'Запушена'), ('F', 'Завершена')], default=('C', 'Создана'), max_length=1, verbose_name='статус'),
        ),
    ]
