# Generated by Django 4.2.4 on 2023-09-02 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_email', '0008_alter_email_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='frequency',
            field=models.CharField(choices=[('ONCE', 'Единоразово'), ('DAILY', 'Ежедневно'), ('weekly', 'Еженедельно'), ('monthly', 'Ежемесячно')], max_length=35, verbose_name='частота'),
        ),
        migrations.AlterField(
            model_name='email',
            name='status',
            field=models.CharField(choices=[('C', 'Создана'), ('L', 'Запушена'), ('F', 'Завершена')], default='C', max_length=30, verbose_name='статус'),
        ),
    ]
