# Generated by Django 4.2.4 on 2023-09-02 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_email', '0009_alter_email_frequency_alter_email_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='status',
            field=models.CharField(choices=[('CREATEDСОЗДАНА', 'Created'), ('LAUNCHEDЗАПУШЕНА', 'Launched'), ('FINISHED ЗАВЕРШЕНА', 'Finished')], default='CREATEDСОЗДАНА', max_length=30, verbose_name='статус'),
        ),
    ]
