# Generated by Django 4.2.4 on 2023-09-02 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_email', '0011_alter_email_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='frequency',
            field=models.CharField(choices=[('Once', 'Единоразово'), ('Daily', 'Ежедневно'), ('Weekly', 'Еженедельно'), ('Monthly', 'Ежемесячно')], max_length=35, verbose_name='частота'),
        ),
        migrations.AlterField(
            model_name='email',
            name='status',
            field=models.CharField(choices=[('Created', 'Создана'), ('Launched', 'Запушена'), ('Finished', ' Завершена')], default='Created', max_length=30, verbose_name='статус'),
        ),
    ]
