# Generated by Django 4.2.4 on 2023-09-05 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_email', '0014_remove_email_send_date_remove_email_send_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='активен'),
        ),
    ]
